### PR TITLE
Hotfix for Qfep analysis tool

### PR DESCRIPTION
**Pull request by acmnpv**
Was missing fix from old version to use of different number of
off-diagonal elements. Added now

### CODE REVIEW

**Review by mpurg — CHANGES_REQUESTED** [review]
Please revise, I noticed some nnoffd-s in there (line 496).
There's also some hardcoded numbers in around that area (495-498) that were fixed in q5 already.

**Comment by acmnpv** [comment]
Made the requested changes. Should be fine now.

**Review by mpurg — CHANGES_REQUESTED** [review]
You missed a 4.0_prec on line 495

**Comment by mpurg** [comment]
I will write up a test for this tomorrow.

**Comment by mpurg** [comment]
[asdasdasd.zip](https://github.com/qusers/Q6/files/1485521/asdasdasd.zip)

Here's the test.

**Comment by esguerra** [comment]
Nice!
How did you come across the struct module?
I didn't know it.
How not to love python darn it!

**Pull request merged**
